name: LAPRAS Card

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-card:
    name: LAPRAS Card
    runs-on: ubuntu-latest
    steps:
      - uses: kawamataryo/lapras-card-readme@main
        with:
          SHARE_ID: '2RTLJAV'
          ICON_FIRST: "#367d5c"
          ICON_SECOND: "#1fd13d"
          BACKGROUND_FIRST: "#92a09a"
          BACKGROUND_SECOND: "#21a108"
          LANG: "ja"
